// BOMCard.jsx — Preliminary Bill of Materials
// Displays the BOM generated by bom.py, grouped by category.
// Includes a CSV export button for procurement handoff.

import { useState } from "react";

const CAT_LABELS = {
  SHAFT: "Shaft & Hub",
  PULLEY: "Pulley Assembly",
  BELT: "Belt & Buckets",
  DRIVE: "Drive Train",
  "TAKE-UP": "Take-Up System",
  CASING: "Casing & Structure",
  CHUTE: "Discharge Chute",
  BEARINGS: "Bearings",
  FASTENERS: "Fasteners",
};

const CAT_COLORS = {
  SHAFT: "#4a9eff",
  PULLEY: "#2dd4bf",
  BELT: "#a78bfa",
  DRIVE: "#1fb86e",
  "TAKE-UP": "#d98e00",
  CASING: "#5a7a9a",
  CHUTE: "#c8192e",
  BEARINGS: "#4a9eff",
  FASTENERS: "#7a9ab8",
};

function downloadCSV(items) {
  const header = [
    "Pos",
    "Tag",
    "Description",
    "Qty",
    "Unit",
    "Material",
    "Standard",
    "Spec",
    "Mass_ea_kg",
    "Mass_tot_kg",
    "Category",
    "Notes",
  ];
  const rows = items.map((i) => [
    i.pos,
    i.tag,
    `"${i.description}"`,
    i.qty,
    i.unit,
    `"${i.material}"`,
    i.standard,
    `"${i.spec}"`,
    i.mass_ea_kg,
    i.mass_tot_kg,
    i.category,
    `"${i.notes || ""}"`,
  ]);
  const csv = [header, ...rows].map((r) => r.join(",")).join("\n");
  const blob = new Blob([csv], { type: "text/csv" });
  const url = URL.createObjectURL(blob);
  const a = Object.assign(document.createElement("a"), {
    href: url,
    download: "BE-001-BOM.csv",
  });
  a.click();
  URL.revokeObjectURL(url);
}

export default function BOMCard({ results }) {
  const bom = results?.bom;
  const [expanded, setExpanded] = useState({});

  if (!bom) {
    return (
      <div style={{ padding: 12, fontSize: 10, color: "var(--text3)" }}>
        BOM not available — run calculation first.
      </div>
    );
  }

  const { items, summary, notes } = bom;
  const byCategory = {};
  for (const item of items) {
    if (!byCategory[item.category]) byCategory[item.category] = [];
    byCategory[item.category].push(item);
  }

  const toggle = (cat) => setExpanded((e) => ({ ...e, [cat]: !e[cat] }));

  return (
    <div style={{ borderTop: "1px solid var(--border)" }}>
      {/* Header */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          padding: "10px 12px 6px",
          borderBottom: "1px solid var(--border)",
        }}
      >
        <div>
          <span
            style={{
              fontSize: 9,
              fontWeight: 700,
              letterSpacing: ".08em",
              textTransform: "uppercase",
              color: "var(--text3)",
            }}
          >
            Preliminary BOM
          </span>
          <span style={{ fontSize: 9, color: "var(--muted)", marginLeft: 8 }}>
            {items.length} items · {summary.total_mass_kg.toLocaleString()} kg
            total
          </span>
        </div>
        <button
          onClick={() => downloadCSV(items)}
          style={{
            padding: "3px 10px",
            fontSize: 9,
            fontWeight: 600,
            borderRadius: 4,
            cursor: "pointer",
            border: "1px solid var(--border)",
            background: "var(--panel2)",
            color: "var(--primary)",
          }}
        >
          ↓ CSV
        </button>
      </div>

      {/* Category groups */}
      {Object.entries(byCategory).map(([cat, catItems]) => {
        const open = expanded[cat] !== false; // default open
        const color = CAT_COLORS[cat] || "#5a7a9a";
        const mass = catItems.reduce((s, i) => s + (i.mass_tot_kg || 0), 0);

        return (
          <div key={cat} style={{ borderBottom: "1px solid var(--border)" }}>
            {/* Category header */}
            <div
              onClick={() => toggle(cat)}
              style={{
                display: "flex",
                alignItems: "center",
                gap: 8,
                padding: "6px 12px",
                cursor: "pointer",
                background: open ? "rgba(255,255,255,.02)" : "transparent",
              }}
              onMouseEnter={(e) =>
                (e.currentTarget.style.background = "rgba(255,255,255,.03)")
              }
              onMouseLeave={(e) =>
                (e.currentTarget.style.background = open
                  ? "rgba(255,255,255,.02)"
                  : "transparent")
              }
            >
              <span
                style={{
                  width: 3,
                  height: 14,
                  borderRadius: 2,
                  background: color,
                  flexShrink: 0,
                }}
              />
              <span
                style={{
                  fontSize: 9.5,
                  fontWeight: 700,
                  color: "var(--text2)",
                  flex: 1,
                }}
              >
                {CAT_LABELS[cat] || cat}
              </span>
              <span
                style={{ fontSize: 8.5, color: "var(--text3)", marginRight: 6 }}
              >
                {mass.toFixed(1)} kg
              </span>
              <span
                style={{
                  fontSize: 9,
                  color: "var(--text3)",
                  transform: open ? "rotate(90deg)" : "rotate(0)",
                  transition: "transform .15s",
                }}
              >
                ›
              </span>
            </div>

            {/* Items table */}
            {open && (
              <div style={{ overflowX: "auto" }}>
                <table
                  style={{
                    width: "100%",
                    borderCollapse: "collapse",
                    fontSize: 9.5,
                  }}
                >
                  <thead>
                    <tr style={{ background: "var(--panel2)" }}>
                      {["#", "Description", "Qty", "Spec", "Mass"].map((h) => (
                        <th
                          key={h}
                          style={{
                            padding: "3px 8px",
                            textAlign: "left",
                            fontSize: 8,
                            color: "var(--text3)",
                            fontWeight: 600,
                            letterSpacing: ".05em",
                            borderBottom: "1px solid var(--border)",
                            whiteSpace: "nowrap",
                          }}
                        >
                          {h}
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {catItems.map((item, i) => (
                      <tr
                        key={item.pos}
                        style={{
                          background:
                            i % 2 === 0
                              ? "transparent"
                              : "rgba(255,255,255,.02)",
                        }}
                      >
                        <td
                          style={{
                            padding: "4px 8px",
                            color: "var(--text3)",
                            fontFamily: "JetBrains Mono,monospace",
                            fontSize: 9,
                          }}
                        >
                          {item.pos}
                        </td>
                        <td
                          style={{ padding: "4px 8px", color: "var(--text2)" }}
                        >
                          <div>{item.description}</div>
                          {item.notes && (
                            <div
                              style={{
                                fontSize: 8,
                                color: "var(--text3)",
                                marginTop: 1,
                              }}
                            >
                              {item.notes}
                            </div>
                          )}
                        </td>
                        <td
                          style={{
                            padding: "4px 8px",
                            color: "var(--text)",
                            fontFamily: "JetBrains Mono,monospace",
                            textAlign: "right",
                            whiteSpace: "nowrap",
                          }}
                        >
                          {item.qty} {item.unit}
                        </td>
                        <td
                          style={{
                            padding: "4px 8px",
                            color: "var(--text3)",
                            fontSize: 8.5,
                            maxWidth: 160,
                            overflow: "hidden",
                            textOverflow: "ellipsis",
                            whiteSpace: "nowrap",
                          }}
                        >
                          {item.spec}
                        </td>
                        <td
                          style={{
                            padding: "4px 8px",
                            color: "var(--text)",
                            fontFamily: "JetBrains Mono,monospace",
                            textAlign: "right",
                            whiteSpace: "nowrap",
                          }}
                        >
                          {item.mass_tot_kg != null
                            ? `${Number(item.mass_tot_kg).toFixed(1)} kg`
                            : "—"}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        );
      })}

      {/* Summary totals */}
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          padding: "8px 12px",
          background: "var(--panel2)",
          borderBottom: "1px solid var(--border)",
        }}
      >
        <span
          style={{
            fontSize: 9,
            fontWeight: 700,
            color: "var(--text3)",
            letterSpacing: ".06em",
            textTransform: "uppercase",
          }}
        >
          Total estimated mass
        </span>
        <span
          style={{
            fontFamily: "JetBrains Mono,monospace",
            fontSize: 13,
            fontWeight: 700,
            color: "var(--primary)",
          }}
        >
          {summary.total_mass_kg.toLocaleString()} kg
        </span>
      </div>

      {/* Notes */}
      <div style={{ padding: "6px 12px 10px" }}>
        {notes.map((n, i) => (
          <div
            key={i}
            style={{
              fontSize: 8.5,
              color: "var(--text3)",
              marginBottom: 2,
              lineHeight: 1.4,
            }}
          >
            * {n}
          </div>
        ))}
      </div>
    </div>
  );
}
